### ISSUE TITLE
Add "EXT2" to modalities

### ISSUE THREAD

**Issue by berndf** [datsyl/fmri-physio-log#4]
Dear Andrew,
we've encountered physio files with not only "EXT" but "EXT2" "modality" as well.
It was easy to add - I attach the patch.

PS: A single patch file was not accepted, so I zipped it and added one of the physio files in question as well. You may include it as a test case / example if you like.

Thanks and best regards,
Bernd
[add_EXT2.zip](https://github.com/andrewrosss/fmri-physio-log/files/11375853/add_EXT2.zip)

**Comment by andrewrosss** [comment]
@berndf thank you for bringing this to my attention, and thank you for the patch! :) The patch has been merged in v0.3.0.
