### ISSUE TITLE
src/grammar.lark: End of INFO_BODY by "6002" without whitespace can lead to parsing errors

### ISSUE THREAD

**Issue by berndf** [datsyl/fmri-physio-log#5]
[INFO_BODY_END.zip](https://github.com/user-attachments/files/15926061/INFO_BODY_END.zip)
I was bitten by the error message "Unexpected token Token('INFO_BODY', '.493774 ...')" and found that it was one of the rare cases in which '6002' occurs as part of a floating-poing number occuring in the INFO_BODY (in this case, the value '61.496002').

This can be fixed by making a space mandatory before (and after) 6002 in the INFO_BODY regex.

The patch and the example file (may be included in with the package if you wish) are in the attached zip file.

**Comment by andrewrosss** [comment]
@berndf You are totally correct. Thank you for the report and the patch! :) I've included the sample (sent as part of the zip) as one of the test cases, and the fix/patch is now in `v0.3.3`.
